openapi: 3.0.0
info:
  description: Near node.js service Open API specification
  version: v1
  title: Near node.js service

tags:
  - name: Account
    description: Operations with near account
  - name: Contract
    description: Operations with contract

servers:
  - url: http://localhost:3000/api/v1

paths:
  /accounts/:
    post:
      tags:
        - Account
      description: Create new account
      requestBody:
        $ref: "#/components/requestBodies/CreateAccountRequest"
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateAccountResponse"
        500:
          description: Internal Server Error
  /accounts/{accountId}/balance:
    get:
      tags:
        - Account
      description: Get account balance
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountBalanceResponse"
        500:
          description: Internal Server Error
  /accounts/{accountId}/contracts/{contractId}/ft-balance:
    get:
      tags:
        - Account
      description: Get the balance of fungible tokens in the account
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
        - name: contractId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FTBalanceResponse"
        500:
          description: Internal Server Error

  /accounts/{accountId}/contracts/{contractId}/nft-list:
    get:
      tags:
        - Account
      description: Get list of nfts
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
        - name: contractId
          in: path
          required: true
          schema:
            type: string
        - name: fromIndex
          in: query
          required: false
          schema:
            type: string
        - name: limit
          in: query
          required: false
          schema:
            type: number
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/NFTResponse"
        500:
          description: Internal Server Error

  /accounts/{accountId}/contracts/{contractId}/nft-supply:
    get:
      tags:
        - Account
      description: Get nft supply for owner
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
        - name: contractId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
        500:
          description: Internal Server Error

  /contracts/{contractId}/login-url:
    get:
      tags:
        - Contract
      description: Creates an access key and generates a URL for authorization in the wallet
      parameters:
        - name: contractId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties: 
                  loginUrl:
                    type: string                

  /contracts/transaction-url:
    post:
      tags:
        - Contract
      description: Generates a URL to confirm a transaction
      requestBody:
        $ref: "#/components/requestBodies/GetTransactionUrlRequest"
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: string

  /contracts/view:
    post:
      tags:
        - Contract
      description: Invoke a contract view function
      requestBody:
        $ref: "#/components/requestBodies/ViewContractFunctionRequest"
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object


components:
  requestBodies:
    CreateAccountRequest:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CreateAccountRequest"
      description: Request model for create new account
      required: true

    GetLoginUrlRequest:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/GetLoginUrlRequest"
      description: Request model for getting login url
      required: true

    GetTransactionUrlRequest:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/GetTransactionUrlRequest"
      description: Request model for getting transaction signature url
      required: true

    ViewContractFunctionRequest:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ViewContractFunctionRequest"
      description: Request model for invoke view contract function
      required: true

  schemas:

    CreateAccountRequest:
      type: object
      required: [ name ]
      properties:
        name:
          type: string
        amount:
          type: string

    GetLoginUrlRequest:
      type: object
      required: [ contractId, successUrl, failureUrl]
      properties:
        contractId:
          type: string
        successUrl:
          type: string
        failureUrl:
          type: string
        methods:
          type: array
          items:
            type: string

    GetTransactionUrlRequest:
      type: object
      properties:
        signerId:
          type: string
        receiverId:
          type: string
        method:
          type: string
        params:
          type: object
        gas:
          type: string
        deposit:
          type: string
        callbackUrl:
          type: string

    ViewContractFunctionRequest:
      type: object
      properties:
        contractId:
          type: string
        method:
          type: string
        params:
          type: object

    CreateAccountResponse:
      type: object
      properties:
        accountId:
          type: string
        publicKey:
          type: string

    NFTResponse:
      type: object
      properties:
        tokenId:
          type: string
        ownerId:
          type: string
        title:
          type: string
        description:
          type: string
        media:
          type: string
        copies:
          type: number
        mediaHash:
          type: string
        issuedAt:
          type: number
        expiresAt:
          type: number
        startsAt:
          type: number
        updatedAt:
          type: number
        extra:
          type: string
        reference:
          type: string
        referenceHash:
          type: string


    FTBalanceResponse:
      type: object
      description: Response model for the balance of fungible tokens in the account
      properties:
        tokenName:
          type: string
        symbol:
          type: string
        icon:
          type: string
        balance:
          type: string


    AccountBalanceResponse:
      type: object
      description: Responce model for the account balance
      properties:
        total:
          type: string
        stateStaked:
          type: string
        staked:
          type: string
        available:
          type: string
